function decisionRow = buildStageRationale(stage, whatChanged, controllingFactor, ...
    assignedStatus, uncertainty, recommendedAction, evidenceNeededNext)

%BUILDSTAGERATIONALE Package one stage's six-question answers.
%
% Six required questions:
%   Q1 - What changed?
%   Q2 - Which calculation/measurement controls the risk?
%   Q3 - What status do you assign, and why?
%   Q4 - What uncertainty remains?
%   Q5 - What action/escalation do you recommend?
%   Q6 - What evidence do you require next?
%
% Confirmed is TRUE only when all six answers contain
% non-whitespace text.

    % ============================================================
    % CONVERT EACH TEXTAREA VALUE TO ONE STRING
    % ============================================================
    
    whatChanged = strjoin(string(whatChanged), " ");
    controllingFactor = strjoin(string(controllingFactor), " ");
    assignedStatus = strjoin(string(assignedStatus), " ");
    uncertainty = strjoin(string(uncertainty), " ");
    recommendedAction = strjoin(string(recommendedAction), " ");
    evidenceNeededNext = strjoin(string(evidenceNeededNext), " ");


    % ============================================================
    % CHECK THAT ALL SIX QUESTIONS HAVE BEEN ANSWERED
    % ============================================================
    
    answers = { ...
        whatChanged, ...
        controllingFactor, ...
        assignedStatus, ...
        uncertainty, ...
        recommendedAction, ...
        evidenceNeededNext};


    allFilled = all(cellfun(@(a) ...
        strlength(strtrim(a)) > 0, ...
        answers));


    % ============================================================
    % BUILD DECISION ROW
    % ============================================================
    
    decisionRow = table( ...
        stage, ...
        whatChanged, ...
        controllingFactor, ...
        assignedStatus, ...
        uncertainty, ...
        recommendedAction, ...
        evidenceNeededNext, ...
        allFilled, ...
        'VariableNames', { ...
            'Stage', ...
            'WhatChanged', ...
            'ControllingFactor', ...
            'AssignedStatus', ...
            'Uncertainty', ...
            'RecommendedAction', ...
            'EvidenceNeededNext', ...
            'Confirmed'});

end